import { Product } from './types/Product'

export const sampleProduct: Product[] = [
  {
    name: 'Nike Slim shirt',
    slug: 'nike-slim-shirt',
    image: '../images/p1.jpg',
    category: 'Shirts',
    brand: 'Nike',
    price: 120,
    countInStock: 10,
    description: 'high quality shirt',
    rating: 4.5,
    numReviews: 10,
  },
  {
    name: 'Adidas Fit shirt',
    slug: 'adidas-fit-shirt',
    image: '../images/p2.jpg',
    category: 'Shirts',
    brand: 'Adidas',
    price: 100,
    countInStock: 10,
    description: 'high quality shirt',
    rating: 4.0,
    numReviews: 10,
  },
  {
    name: 'Lacost Free Pants',
    slug: 'Lacost-free-pants',
    image: '../images/p3.jpg',
    category: 'Pants',
    brand: 'Lacost',
    price: 220,
    countInStock: 0,
    description: 'high quality Pants',
    rating: 4.8,
    numReviews: 17,
  },
  {
    name: 'Nike Slim Pant',
    slug: 'nike-slim-pant',
    image: '../images/p4.jpg',
    category: 'Pants',
    brand: 'Nike',
    price: 78,
    countInStock: 15,
    description: 'high quality Pant',
    rating: 4.5,
    numReviews: 14,
  },
]
